### ISSUE TITLE
The code is deprecated and not work in Flutter Stable 2.5

### ISSUE THREAD

**Issue by moinkhan780** [beerstorm-net/GeoFlutterFire2#4]
Kindly update this package otherwise it will not work for a-lot of people's who using the latest flutter version.

**Comment by LucaDillenburg** [comment]
Hi @moinkhan780 , I forked and updated the package. It's running smoothly with Flutter 2.5 and now supports the ```withConverter``` method from the ```cloud_firestore``` package.

I opened a Pull Request here: #5 .

You can choose to wait for it to get updated in ```pub.dev``` or use the code directly from the forked repo. For the latter, use:
```yaml
    geoflutterfire2:
      git:
        url: https://github.com/LucaDillenburg/GeoFlutterFire2
        ref: b5badaef3bbe905a0fbe1f31304d08a85c62d7de
```
